<?php

declare(strict_types=1);

namespace DrevOps\VortexTooling\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

/**
 * Tests for notify-newrelic script.
 *
 * @phpcs:disable Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing
 */
#[RunTestsInSeparateProcesses]
#[Group('notify')]
class NotifyNewrelicTest extends UnitTestCase {

  protected function setUp(): void {
    parent::setUp();

    $this->envSetMultiple([
      'VORTEX_NOTIFY_NEWRELIC_ENABLED' => 'true',
      'VORTEX_NOTIFY_NEWRELIC_PROJECT' => 'test-project',
      'VORTEX_NOTIFY_NEWRELIC_USER_KEY' => 'NRAK-TEST123456',
      'VORTEX_NOTIFY_NEWRELIC_LABEL' => 'main',
      'VORTEX_NOTIFY_NEWRELIC_ENVIRONMENT_URL' => 'https://example.com',
      'VORTEX_NOTIFY_NEWRELIC_LOGIN_URL' => 'https://example.com/login',
      'VORTEX_NOTIFY_NEWRELIC_APP_NAME' => 'test-app',
      'VORTEX_NOTIFY_NEWRELIC_USER' => 'Deploy Bot',
      'VORTEX_NOTIFY_NEWRELIC_EVENT' => 'post_deployment',
      'VORTEX_NOTIFY_NEWRELIC_APPID' => '12345678',
    ]);
  }

  public function testNotificationSkippedWhenNotEnabled(): void {
    $this->envUnset('VORTEX_NOTIFY_NEWRELIC_ENABLED');

    $this->runScriptEarlyPass('src/notify-newrelic', 'New Relic is not enabled');
  }

  public function testNotificationEnabledWithFallbackVariable(): void {
    $this->envUnset('VORTEX_NOTIFY_NEWRELIC_ENABLED');
    $this->envSet('NEWRELIC_ENABLED', 'true');
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v1.0.0');

    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(fn(): true => TRUE),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Started New Relic notification', $output);
    $this->assertStringContainsString('Finished New Relic notification', $output);
  }

  public function testSuccessfulNotificationWithProvidedAppId(): void {
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v1.2.3');

    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(function ($body): true {
        /** @var array{deployment: array{revision: string, user: string}} $payload */
        $payload = json_decode($body, TRUE);
        $this->assertEquals('v1.2.3', $payload['deployment']['revision']);
        $this->assertEquals('Deploy Bot', $payload['deployment']['user']);
        return TRUE;
      }),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201, 'body' => '{"deployment": {"id": 999}}']
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Started New Relic notification', $output);
    $this->assertStringContainsString('Project          : test-project', $output);
    $this->assertStringContainsString('App ID (resolved): 12345678', $output);
    $this->assertStringContainsString('Revision         : v1.2.3', $output);
    $this->assertStringContainsString('Finished New Relic notification', $output);
  }

  public function testSuccessfulNotificationWithAutoGeneratedRevision(): void {
    // Don't set revision - should auto-generate.
    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(function ($body): true {
        /** @var array{deployment: array{revision: string}} $payload */
        $payload = json_decode($body, TRUE);
        // Verify format: LABEL-YYYYMMDD-HHMMSS.
        $this->assertMatchesRegularExpression('/^main-\d{8}-\d{6}$/', $payload['deployment']['revision']);
        return TRUE;
      }),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Auto-generated revision:', $output);
    $this->assertMatchesRegularExpression('/main-\d{8}-\d{6}/', $output);
  }

  public function testSuccessfulNotificationWithAutoDiscoveredAppId(): void {
    // Don't provide app ID.
    $this->envUnset('VORTEX_NOTIFY_NEWRELIC_APPID');

    // Mock app ID discovery.
    $this->mockRequestGet(
      'https://api.newrelic.com/v2/applications.json?filter[name]=test-app&exclude_links=true',
      ['Api-Key: NRAK-TEST123456'],
      10,
      ['status' => 200, 'body' => '{"applications": [{"id": 87654321, "name": "test-app"}]}']
    );

    // Mock deployment creation.
    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/87654321/deployments.json',
      $this->callback(fn(): true => TRUE),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Discovering APP id by name', $output);
    $this->assertStringContainsString('App ID (resolved): 87654321', $output);
    $this->assertStringContainsString('Finished New Relic notification', $output);
  }

  public function testNotificationSkippedWhenNoAppIdFound(): void {
    $this->envUnset('VORTEX_NOTIFY_NEWRELIC_APPID');

    // Mock app ID discovery returning empty.
    $this->mockRequestGet(
      'https://api.newrelic.com/v2/applications.json?filter[name]=test-app&exclude_links=true',
      ['Api-Key: NRAK-TEST123456'],
      10,
      ['status' => 200, 'body' => '{"applications": []}']
    );

    $this->runScriptEarlyPass('src/notify-newrelic', 'Notification skipped: No New Relic application ID found');
  }

  public function testPreDeploymentEventSkipped(): void {
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_EVENT', 'pre_deployment');

    $this->runScriptEarlyPass('src/notify-newrelic', 'Skipping New Relic notification for pre_deployment event');
  }

  public function testSuccessfulNotificationWithCustomDescription(): void {
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_DESCRIPTION', '%project% deployed to %label% at %timestamp%');
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v2.0.0');

    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(function ($body): true {
        /** @var array{deployment: array{description: string}} $payload */
        $payload = json_decode($body, TRUE);
        $this->assertStringContainsString('test-project deployed to main', $payload['deployment']['description']);
        return TRUE;
      }),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('test-project deployed to main', $output);
  }

  public function testSuccessfulNotificationWithCustomChangelog(): void {
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v2.0.0');
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_CHANGELOG', 'Fixed bug #123 and added feature XYZ');

    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(function ($body): true {
        /** @var array{deployment: array{changelog: string}} $payload */
        $payload = json_decode($body, TRUE);
        $this->assertEquals('Fixed bug #123 and added feature XYZ', $payload['deployment']['changelog']);
        return TRUE;
      }),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Finished New Relic notification', $output);
  }

  public function testSuccessfulNotificationWithCustomEndpoint(): void {
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_ENDPOINT', 'https://api.eu.newrelic.com/v2');
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v1.0.0');

    $this->mockRequestPost(
      'https://api.eu.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(fn(): true => TRUE),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Endpoint         : https://api.eu.newrelic.com/v2', $output);
    $this->assertStringContainsString('Finished New Relic notification', $output);
  }

  public function testNotificationFailureWhenDeploymentCreationFails(): void {
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v1.0.0');

    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(fn(): true => TRUE),
      ['Api-Key: NRAK-TEST123456', 'Content-Type: application/json'],
      10,
      ['status' => 500, 'body' => 'Internal Server Error']
    );

    $this->runScriptError('src/notify-newrelic', 'Failed to create a deployment notification');
  }

  #[DataProvider('dataProviderMissingRequiredVariables')]
  public function testMissingRequiredVariables(string $var_name): void {
    $this->envUnset($var_name);
    $this->runScriptError('src/notify-newrelic', 'Missing required New Relic User API Key');
  }

  public static function dataProviderMissingRequiredVariables(): array {
    return [
      'user_key' => ['VORTEX_NOTIFY_NEWRELIC_USER_KEY'],
    ];
  }

  public function testFallbackToGenericVariables(): void {
    $this->envUnsetMultiple([
      'VORTEX_NOTIFY_NEWRELIC_PROJECT',
      'VORTEX_NOTIFY_NEWRELIC_USER_KEY',
      'VORTEX_NOTIFY_NEWRELIC_LABEL',
    ]);
    $this->envSet('VORTEX_NOTIFY_NEWRELIC_REVISION', 'v1.0.0');

    $this->envSet('VORTEX_NOTIFY_PROJECT', 'fallback-project');
    $this->envSet('NEWRELIC_USER_KEY', 'NRAK-FALLBACK456');
    $this->envSet('VORTEX_NOTIFY_LABEL', 'develop');

    $this->mockRequestPost(
      'https://api.newrelic.com/v2/applications/12345678/deployments.json',
      $this->callback(function ($body): true {
        /** @var array{deployment: array{description: string}} $payload */
        $payload = json_decode($body, TRUE);
        $this->assertStringContainsString('fallback-project', $payload['deployment']['description']);
        return TRUE;
      }),
      ['Api-Key: NRAK-FALLBACK456', 'Content-Type: application/json'],
      10,
      ['status' => 201]
    );

    $output = $this->runScript('src/notify-newrelic');

    $this->assertStringContainsString('Project          : fallback-project', $output);
    $this->assertStringContainsString('Deployment       : develop', $output);
  }

}
