docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    #:
    #: Helper command to discover available variables. Remove in production.
    - run:
        name: env variables
        command: env
        service: cli

    - run:
        name: Download database
        command: |
          #; If Lagoon is used as non-prod environment and the database is
          #; located elsewhere, we need to get access to that remote
          #; environmnent to download the database dump.
          #;
          #;< ACQUIA
          #: If source DB is in Acquia, we need to be able to use Cloud API
          #: to download the database dump. In order to do so, we need to
          #: provide Cloud API credentials in AC_API_USER_NAME and AC_API_USER_PASS
          #: variables, which can be either set in your .env file and stored in
          #: the git repository (not the best practice) or through GraphQL query
          #: in Lagoon (need to contact Amazee support).
          #;> ACQUIA
          #: Import variables from .env file.
          t=$(mktemp) && export -p > "$t" && set -a && . ./.env && set +a && . "$t" && rm "$t" && unset t
          #:
          #: Override resulting file (since we are running in container and
          #: data should be stored outside of the codebase) and download backup.
          DB_DIR=/tmp/data ./scripts/drevops/download-db.sh
        service: cli

    - run:
        name: Install site
        command: ./scripts/drevops/drupal-install-site.sh
        service: cli
        shell: bash

environments:
  master:
    types:
      mariadb: mariadb-shared
    cronjobs:
      - name: drush cron
        schedule: '*/15 * * * *'
        command: drush cron --root=/app
        service: cli
    routes:
      - nginx:
          - your-site-url:
              tls-acme: 'true'
          - www.your-site-url:
              tls-acme: 'false'
    monitoring_urls:
      - your-site-url
      - www.your-site-url
routes:
  insecure: Redirect
