ARG CLI_IMAGE
FROM ${CLI_IMAGE:-builder} as builder

FROM amazeeio/nginx-drupal

ENV WEBROOT=docroot

COPY docker/drupal.conf /etc/nginx/conf.d/app.conf
RUN fix-permissions /etc/nginx

COPY --from=builder /app /app
