#!/usr/bin/env sh
#
# Get the status of XDebug in PHP CLI as a string and return a code.
#

verbose="${1:-}"

if php -v | grep -q Xdebug; then
  [ -n "${verbose}" ] && echo "Enabled";
  exit 0
fi

[ -n "${verbose}" ] && echo "Disabled";
exit 1
