#!/usr/bin/env php
<?php

/**
 * @file
 * Deploy code to a remote location.
 *
 * Deployment may include pushing code, pushing created container image,
 * notifying remote hosting service via webhook call etc.
 *
 * Multiple deployments can be configured by providing a comma-separated list of
 * deployment types in $VORTEX_DEPLOY_TYPES variable.
 *
 * Deployments can be skipped by setting the $VORTEX_DEPLOY_SKIP variable
 * to "1".
 *
 * This is a router script to call relevant scripts based on type.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';
execute_override(basename(__FILE__));

// -----------------------------------------------------------------------------

// The types of deployment.
//
// Can be a combination of comma-separated values (to support multiple
// deployments): code, container_registry, webhook, lagoon.
$deploy_types = getenv_default('VORTEX_DEPLOY_TYPES', '');
$deploy_types = !empty($deploy_types) ? array_map('trim', explode(',', $deploy_types)) : [];

// Deployment mode.
//
// Values can be one of: branch, tag.
$deploy_mode = getenv_default('VORTEX_DEPLOY_MODE', 'branch');

// Deployment action.
//
// Values can be one of: deploy, deploy_override_db, destroy.
// - deploy: Deploy code and preserve database in the environment.
// - deploy_override_db: Deploy code and override database in the environment.
// - destroy: Destroy the environment (if the provider supports it).
$deploy_action = getenv_default('VORTEX_DEPLOY_ACTION', 'deploy');

// Deployment branch name.
$deploy_branch = getenv_default('VORTEX_DEPLOY_BRANCH', NULL);

// Deployment pull request number without "pr-" prefix.
$deploy_pr = getenv_default('VORTEX_DEPLOY_PR', NULL);

// Flag to skip all deployments.
$deploy_skip = getenv_default('VORTEX_DEPLOY_SKIP', FALSE);

// Flag to allow skipping of a deployment using additional flags.
$deploy_allow_skip = getenv_default('VORTEX_DEPLOY_ALLOW_SKIP', FALSE);

// Allow skipping deployment by providing `$VORTEX_DEPLOY_SKIP_BRANCHES`
// variable with branch names as a single value or comma-separated list.
//
// Branch names must match exactly as they appear in the repository.
//
// Examples:
// VORTEX_DEPLOY_SKIP_BRANCHES=feature/test
// VORTEX_DEPLOY_SKIP_BRANCHES=feature/test,hotfix/urgent,project/experimental
$deploy_allow_skip_branches = getenv_default('VORTEX_DEPLOY_SKIP_BRANCHES', '');
$deploy_allow_skip_branches = array_map('trim', explode(',', $deploy_allow_skip_branches));

// Allow skipping deployment by providing `$VORTEX_DEPLOY_SKIP_PRS` variable
// with PR numbers as a single value or comma-separated list.
//
// Examples:
// VORTEX_DEPLOY_SKIP_PRS=123
// VORTEX_DEPLOY_SKIP_PRS=123,456,789
$deploy_allow_skip_prs = getenv_default('VORTEX_DEPLOY_SKIP_PRS', '');
$deploy_allow_skip_prs = array_map('trim', explode(',', $deploy_allow_skip_prs));

// -----------------------------------------------------------------------------

info('Started deployment.');

if (!empty($deploy_skip)) {
  note('Found flag to skip all deployments.');
  pass(sprintf('Skipping deployment %s.', implode(',', $deploy_types)));
  quit(0);
}

if (empty($deploy_types)) {
  fail('Missing required value for VORTEX_DEPLOY_TYPES. Must be a combination of comma-separated values (to support multiple deployments): code, container_registry, webhook, lagoon.');
}

// Check for conditional skip flags.
if (!empty($deploy_allow_skip)) {
  note('Found flag to skip a deployment.');

  if (!empty($deploy_pr) && !empty($deploy_allow_skip_prs) && in_array($deploy_pr, $deploy_allow_skip_prs, TRUE)) {
    note(sprintf('Found PR %s in skip list.', $deploy_pr));
    note(sprintf('Skipping deployment %s.', implode(',', $deploy_types)));
    quit(0);
  }

  if (!empty($deploy_branch) && !empty($deploy_allow_skip_branches) && in_array($deploy_branch, $deploy_allow_skip_branches, TRUE)) {
    note(sprintf('Found branch %s in skip list.', $deploy_branch));
    note(sprintf('Skipping deployment %s.', implode(',', $deploy_types)));
    quit(0);
  }
}

// Route to deployment scripts based on type.
if (in_array('artifact', $deploy_types, TRUE)) {
  if ($deploy_mode === 'tag') {
    putenv('VORTEX_DEPLOY_ARTIFACT_DST_BRANCH=deployment/[tags:-]');
  }

  passthru(__DIR__ . '/deploy-artifact', $exit_code);
  $exit_code && quit($exit_code);
}

if (in_array('webhook', $deploy_types, TRUE)) {
  passthru(__DIR__ . '/deploy-webhook', $exit_code);
  $exit_code && quit($exit_code);
}

if (in_array('container_registry', $deploy_types, TRUE)) {
  passthru(__DIR__ . '/deploy-container-registry', $exit_code);
  $exit_code && quit($exit_code);
}

if (in_array('lagoon', $deploy_types, TRUE)) {
  passthru(__DIR__ . '/deploy-lagoon', $exit_code);
  $exit_code && quit($exit_code);
}

pass('Finished deployment.');
quit(0);
