#!/usr/bin/env php
<?php

/**
 * @file
 * Deploy exported database container image to the container registry.
 *
 * IMPORTANT! This script runs outside the container on the host system.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Container image to deploy in a form of '<org>/<repository>'.
$db_image = getenv_default('VORTEX_EXPORT_DB_IMAGE', 'VORTEX_DB_IMAGE', '');

// Whether to proceed with the deployment.
$registry_deploy = getenv_default('VORTEX_EXPORT_DB_CONTAINER_REGISTRY_DEPLOY_PROCEED', '0');

// -----------------------------------------------------------------------------

info('Started database container image deployment.');

if ($registry_deploy !== '1') {
  pass('Skipped database container image deployment as VORTEX_EXPORT_DB_CONTAINER_REGISTRY_DEPLOY_PROCEED is not set to 1.');
  quit(0);
}

if ($db_image === '') {
  fail('Container image name is not specified. Please provide container image as a variable VORTEX_EXPORT_DB_IMAGE in a format <org>/<repository>.');
}

putenv('VORTEX_DEPLOY_CONTAINER_REGISTRY_MAP=database=' . $db_image);
passthru_or_fail(__DIR__ . '/deploy-container-registry', 'Failed to deploy database container image to registry.');

pass('Finished database container image deployment.');
