#!/usr/bin/env php
<?php

/**
 * @file
 * Log out an admin from a Drupal site.
 *
 * IMPORTANT! This script runs inside the container.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';
execute_override(basename(__FILE__));

// -----------------------------------------------------------------------------

// Flag to block admin on logout.
$block_admin = getenv_default('VORTEX_LOGOUT_BLOCK_ADMIN', 'VORTEX_UNBLOCK_ADMIN', '1');

// -----------------------------------------------------------------------------

if ($block_admin === '1') {
  passthru('./vendor/bin/drush -y sql:query "SELECT name FROM `users_field_data` WHERE `uid` = \'1\';" | head -n 1 | xargs ./vendor/bin/drush -y -- user:block', $exit_code);
  if ($exit_code !== 0) {
    fail('Failed to block admin user.');
  }
}
