#!/usr/bin/env php
<?php

/**
 * @file
 * Log out an admin from a Drupal site.
 *
 * IMPORTANT! This script runs inside the container.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Flag to block admin on logout.
$block_admin = getenv_default('VORTEX_LOGOUT_BLOCK_ADMIN', 'VORTEX_UNBLOCK_ADMIN', '1');

// -----------------------------------------------------------------------------

if ($block_admin === '1') {
  $admin_name_output = (string) shell_exec('./vendor/bin/drush -y sql:query "SELECT name FROM \\`users_field_data\\` WHERE \\`uid\\` = \'1\';"');
  $admin_name = trim(explode("\n", trim($admin_name_output))[0]);

  if ($admin_name !== '') {
    passthru_or_fail(sprintf('./vendor/bin/drush -y -- user:block %s', escapeshellarg($admin_name)), 'Failed to block admin user.');
  }
}
