#!/usr/bin/env php
<?php

/**
 * @file
 * Reset project to a freshly cloned repository state.
 *
 * IMPORTANT! This script runs outside the container on the host system.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Name of the webroot directory with Drupal codebase.
$webroot = getenv_default('WEBROOT', 'web');

// -----------------------------------------------------------------------------

command_must_exist('git');

$is_hard_reset = in_array('--hard', array_slice($GLOBALS['argv'], 1), TRUE);

INFO('Started reset.');

TASK('Removing dependencies and built assets.', 'Removed dependencies and built assets.', function () use ($webroot): void {
  passthru(sprintf('rm -rf "./vendor" "./%s/core" "./%s/profiles/contrib" "./%s/modules/contrib" "./%s/themes/contrib" "./%s/themes/custom/*/build" "./%s/themes/custom/*/scss/_components.scss"', $webroot, $webroot, $webroot, $webroot, $webroot, $webroot));
});

TASK('Removing node_modules directories.', 'Removed node_modules directories.', function (): void {
  passthru('find . -type d -name node_modules -prune -exec rm -Rf -- {} +', $exit_code);
  if ($exit_code !== 0) {
    throw new \RuntimeException('Failed to remove node_modules directories.');
  }
});

if ($is_hard_reset) {
  TASK('Changing permissions and removing all other untracked files.', 'Changed permissions and removed all other untracked files.', function (): void {
    passthru('git ls-files --others -i --exclude-from=.gitignore -z | xargs -0 -r sh -c \'for f in "$@"; do chmod 777 "$f" 2>/dev/null; rm -rf "$f" 2>/dev/null; done\' _');
  });

  TASK('Resetting repository files.', 'Reset repository files.', function (): void {
    passthru('git reset --hard', $exit_code);
    if ($exit_code !== 0) {
      throw new \RuntimeException('Failed to reset repository files.');
    }
  });

  TASK('Removing all untracked files.', 'Removed all untracked files.', function (): void {
    passthru('git clean -f -d', $exit_code);
    if ($exit_code !== 0) {
      throw new \RuntimeException('Failed to remove untracked files.');
    }
  });

  TASK('Removing empty directories.', 'Removed empty directories.', function (): void {
    passthru('find . -type d -not -path "./.git/*" -empty -delete');
  });
}

PASS('Finished reset.');
