#!/usr/bin/env php
<?php

/**
 * @file
 * Print project information.
 *
 * IMPORTANT! This script runs inside the container.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Name of the webroot directory with Drupal codebase.
$webroot = getenv_default('WEBROOT', 'web');

// Show one-time login link.
$show_login = getenv_default('VORTEX_SHOW_LOGIN', '');

// -----------------------------------------------------------------------------

$sequelace = !empty(getenv('VORTEX_HOST_HAS_SEQUELACE')) ? "('ahoy db' to start SequelAce)" : '';

INFO('Project information:');

echo PHP_EOL;
NOTE('Project name                : %s', getenv('VORTEX_PROJECT') ?: '');
NOTE('Docker Compose project name : %s', getenv('COMPOSE_PROJECT_NAME') ?: '');
NOTE('Site local URL              : http://%s', getenv('LOCALDEV_URL') ?: '');
NOTE('Path to web root            : %s/%s', (string) getcwd(), $webroot);
NOTE('DB host                     : %s', getenv('DATABASE_HOST') ?: '');
NOTE('DB username                 : %s', getenv('DATABASE_USERNAME') ?: '');
NOTE('DB password                 : %s', getenv('DATABASE_PASSWORD') ?: '');
NOTE('DB port                     : %s', getenv('DATABASE_PORT') ?: '');
NOTE('DB port on host             : %s %s', getenv('VORTEX_HOST_DB_PORT') ?: '', $sequelace);

$db_image = getenv('VORTEX_DB_IMAGE') ?: '';
if ($db_image !== '') {
  NOTE('DB-in-image                 : %s', $db_image);
}

$solr_port = getenv('VORTEX_HOST_SOLR_PORT') ?: '';
if ($solr_port !== '') {
  NOTE('Solr URL on host            : http://127.0.0.1:%s', $solr_port);
}

$selenium_vnc_port = getenv('VORTEX_HOST_SELENIUM_VNC_PORT') ?: '';
if ($selenium_vnc_port !== '') {
  NOTE('Selenium VNC URL on host    : http://localhost:%s/?autoconnect=1&password=secret', $selenium_vnc_port);
}

NOTE('Mailhog URL                 : http://mailhog.docker.amazee.io/');

// Check Xdebug status.
$php_version = (string) shell_exec('php -v 2>/dev/null');
$xdebug_status = str_contains($php_version, 'Xdebug')
  ? "Enabled ('ahoy up cli' to disable)"
  : "Disabled ('ahoy debug' to enable)";
NOTE('Xdebug                      : %s', $xdebug_status);

if ($show_login === '1') {
  echo '       Site login link             : ';
  passthru('php ' . __DIR__ . '/vortex-login');
}
else {
  echo PHP_EOL;
  NOTE("Use 'ahoy login' to generate Drupal login link.");
}
echo PHP_EOL;
