#!/usr/bin/env php
<?php

/**
 * @file
 * Export database as a file.
 *
 * IMPORTANT! This script runs inside the container.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Directory with database dump file.
$db_dir = getenv_default('VORTEX_EXPORT_DB_FILE_DIR', 'VORTEX_DB_DIR', './.data');

// Custom dump file name provided as first CLI argument.
$custom_file = $GLOBALS['argv'][1] ?? '';

// -----------------------------------------------------------------------------

info('Started database file export.');

// Create dump file name with a timestamp or use the file name provided.
if ($custom_file !== '') {
  $dump_file = $db_dir . '/' . $custom_file;
}
else {
  $dump_file = $db_dir . '/export_db_' . date('Ymd_His') . '.sql';
}

// If dump file is relative - update it to the parent directory, because the
// `drush sql:dump` command result file is relative to Drupal root.
$dump_file_drush = $dump_file;
if (str_starts_with($dump_file_drush, './')) {
  $dump_file_drush = '../' . substr($dump_file_drush, 2);
}

prepare_db_dir($db_dir);

task(
  'Exporting database to the dump file.',
  sprintf('Exported database dump saved %s.', $dump_file),
  function () use ($dump_file_drush, $dump_file): void {
    drush('sql:dump --skip-tables-key=common --result-file=' . escapeshellarg($dump_file_drush) . ' -q');

    // Check that file was saved.
    if (!file_exists($dump_file) || filesize($dump_file) <= 0) {
      throw new \RuntimeException(sprintf('Unable to save dump file %s.', $dump_file));
    }
  },
);

pass('Finished database file export.');
