#!/usr/bin/env php
<?php

/**
 * @file
 * Download DB dump from FTP.
 *
 * IMPORTANT! This script runs outside the container on the host system.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Database index suffix.
$db_index = getenv_default('VORTEX_DB_INDEX', '');

// The FTP user.
$ftp_user = getenv_required(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_USER', 'VORTEX_FETCH_DB_FTP_USER'])));

// The FTP password.
$ftp_pass = getenv_required(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_PASS', 'VORTEX_FETCH_DB_FTP_PASS'])));

// The FTP host.
$ftp_host = getenv_required(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_HOST', 'VORTEX_FETCH_DB_FTP_HOST'])));

// The FTP port.
$ftp_port = getenv_required(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_PORT', 'VORTEX_FETCH_DB_FTP_PORT'])));

// The file name, including any directories.
$ftp_file = getenv_required(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_FILE', 'VORTEX_FETCH_DB_FTP_FILE'])));

// Directory with database dump file.
$db_dir = getenv_default(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_DB_DIR', 'VORTEX_FETCH_DB' . $db_index . '_DIR', 'VORTEX_DB' . $db_index . '_DIR', 'VORTEX_FETCH_DB_FTP_DB_DIR', 'VORTEX_FETCH_DB_DIR', 'VORTEX_DB_DIR', './.data'])));

// Database dump file name.
$db_file = getenv_default(...array_values(array_unique(['VORTEX_FETCH_DB' . $db_index . '_FTP_DB_FILE', 'VORTEX_FETCH_DB' . $db_index . '_FILE', 'VORTEX_DB' . $db_index . '_FILE', 'VORTEX_FETCH_DB_FTP_DB_FILE', 'VORTEX_FETCH_DB_FILE', 'VORTEX_DB_FILE', 'db.sql'])));

// -----------------------------------------------------------------------------

INFO('Started database dump download from FTP.');

prepare_db_dir($db_dir);

TASK('Downloading the database dump from FTP.', 'Downloaded the database dump from FTP.', function () use ($ftp_host, $ftp_port, $ftp_file, $ftp_user, $ftp_pass, $db_dir, $db_file): void {
  $response = request(sprintf('ftp://%s:%s/%s', $ftp_host, $ftp_port, $ftp_file), ['method' => 'GET', 'auth' => $ftp_user . ':' . $ftp_pass, 'save_to' => $db_dir . '/' . $db_file, 'timeout' => 300]);

  if (!$response['ok']) {
    throw new \RuntimeException('Failed to download database dump from FTP.');
  }
});

PASS('Finished database dump download from FTP.');
