#!/usr/bin/env php
<?php

/**
 * @file
 * Login to a Drupal site as an admin user.
 *
 * IMPORTANT! This script runs inside the container.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Flag to unblock admin.
$unblock_admin = getenv_default('VORTEX_LOGIN_UNBLOCK_ADMIN', 'VORTEX_UNBLOCK_ADMIN', '1');

// -----------------------------------------------------------------------------

if ($unblock_admin === '1') {
  // Check if the password_policy module is enabled.
  $enabled_modules = (string) shell_exec('./vendor/bin/drush -y pm:list --status=enabled 2>/dev/null');
  if (str_contains($enabled_modules, 'password_policy')) {
    passthru('./vendor/bin/drush -y sql:query \'UPDATE `user__field_password_expiration` SET `field_password_expiration_value` = 0 WHERE `bundle` = "user" AND `entity_id` = 1;\' >/dev/null', $exit_code);
  }

  // Unblock the admin user.
  $admin_name_output = (string) shell_exec('./vendor/bin/drush -y sql:query "SELECT name FROM \\`users_field_data\\` WHERE \\`uid\\` = \'1\';"');
  $admin_name = trim(explode("\n", trim($admin_name_output))[0]);

  if ($admin_name !== '') {
    passthru(sprintf('./vendor/bin/drush -y -- user:unblock %s 2>/dev/null', escapeshellarg($admin_name)), $exit_code);
  }
}

passthru_or_fail('./vendor/bin/drush -y user:login');
