#!/usr/bin/env php
<?php

/**
 * @file
 * Export database as a file.
 *
 * IMPORTANT! This script runs inside the container.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/helpers.php';

// -----------------------------------------------------------------------------

// Directory with database dump file.
$db_dir = getenv_default('VORTEX_EXPORT_DB_FILE_DIR', 'VORTEX_DB_DIR', './.data');

// Custom dump file name provided as first CLI argument.
$custom_file = $GLOBALS['argv'][1] ?? '';

// -----------------------------------------------------------------------------

INFO('Started database file export.');

// Create dump file name with a timestamp or use the file name provided.
if ($custom_file !== '') {
  $dump_file = $db_dir . '/' . $custom_file;
}
else {
  $dump_file = $db_dir . '/export_db_' . date('Ymd_His') . '.sql';
}

$dump_file_drush = drush_relative_path($dump_file);

prepare_db_dir($db_dir);

TASK(
  'Exporting database to the dump file.',
  sprintf('Exported database dump saved %s.', $dump_file),
  function () use ($dump_file_drush, $dump_file): void {
    drush('sql:dump --skip-tables-key=common --result-file=' . escapeshellarg($dump_file_drush) . ' -q');

    // Check that file was saved.
    if (!file_exists($dump_file) || filesize($dump_file) <= 0) {
      throw new \RuntimeException(sprintf('Unable to save dump file %s.', $dump_file));
    }
  },
);

PASS('Finished database file export.');
