<?php

/**
 * @file
 * Lagoon hosting provider settings.
 *
 * Do not place any custom settings in this file.
 * It is used to explicitly map provider environments to
 * $settings['environment'] and set platform-specific settings only.
 * Instead, use per-module settings files.
 */

declare(strict_types=1);

if (!empty(getenv('LAGOON_KUBERNETES'))) {
  if (getenv('LAGOON_ENVIRONMENT_TYPE') == 'production') {
    $settings['environment'] = ENVIRONMENT_PROD;
  }
  else {
    $settings['environment'] = ENVIRONMENT_DEV;

    // The environment may not be marked as 'production' in Lagoon yet, so
    // detect the production environment by the branch name as well.
    if (!empty(getenv('LAGOON_GIT_BRANCH')) && !empty(getenv('VORTEX_LAGOON_PRODUCTION_BRANCH')) && getenv('LAGOON_GIT_BRANCH') === getenv('VORTEX_LAGOON_PRODUCTION_BRANCH')) {
      $settings['environment'] = ENVIRONMENT_PROD;
    }
    // Dedicated test environment based on a branch name.
    elseif (getenv('LAGOON_GIT_BRANCH') == 'main' || getenv('LAGOON_GIT_BRANCH') == 'master') {
      $settings['environment'] = ENVIRONMENT_STAGE;
    }
    // Test environment based on a branch prefix for release and
    // hotfix branches.
    elseif (!empty(getenv('LAGOON_GIT_BRANCH'))) {
      $lagoon_git_branch = getenv('LAGOON_GIT_BRANCH');
      if ($lagoon_git_branch && (str_starts_with($lagoon_git_branch, 'release/') || str_starts_with($lagoon_git_branch, 'hotfix/'))) {
        $settings['environment'] = ENVIRONMENT_STAGE;
      }
    }
  }

  if (!defined('LAGOON_VERSION')) {
    define('LAGOON_VERSION', '1');
  }

  $settings['reverse_proxy'] = TRUE;
  $settings['reverse_proxy_header'] = 'HTTP_TRUE_CLIENT_IP';

  $settings['cache_prefix']['default'] = (getenv('LAGOON_PROJECT') ?: getenv('VORTEX_PROJECT')) . '_' . (getenv('LAGOON_GIT_SAFE_BRANCH') ?: getenv('VORTEX_LAGOON_PRODUCTION_BRANCH'));

  // Trusted host patterns for Lagoon internal routes.
  // Do not modify this section. Instead, add your custom patterns to the
  // settings.php file.
  // URL when accessed from PHP processes in Lagoon.
  $settings['trusted_host_patterns'][] = '^nginx\-php$';
  // Trust amazee.io's autogenerated internal routes, served under *.amazee.io.
  $settings['trusted_host_patterns'][] = '^.+\.amazee\.io$';
  $lagoon_routes = getenv('LAGOON_ROUTES');
  if ($lagoon_routes) {
    $lagoon_route_urls = array_map(trim(...), explode(',', $lagoon_routes));
    foreach ($lagoon_route_urls as $lagoon_route_url) {
      $lagoon_route_host = strtolower(str_replace(['https://', 'http://'], '', $lagoon_route_url));
      if (!empty($lagoon_route_host)) {
        $settings['trusted_host_patterns'][] = '^' . preg_quote($lagoon_route_host, '/') . '$';
      }
    }
  }
}
