<?php

/**
 * @file
 * Base module for New hope.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements hook_mail_alter().
 */
function the_force_base_mail_alter(array &$message): void {
  // Allow to stop any mail send out through settings. Note if email
  // functionality needs to be tested, this code should be removed and
  // replaced with a dev mail system.
  if (Settings::get('suspend_mail_send')) {
    $message['send'] = FALSE;
  }
}
