<?php

/**
 * @file
 * Template for star wars theme.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements template_preprocess_html().
 */
function light_saber_preprocess_html(array &$variables): void {
  _light_saber_preprocess_navigation($variables);
}

/**
 * Preprocess administration navigation.
 */
function _light_saber_preprocess_navigation(array &$variables): void {
  // Hide the administration navigation. Useful for theming while logged in as
  // an administrator.
  if (Settings::get('hide_admin_navigation')) {
    unset($variables['page_top']['navigation']);
    unset($variables['page_top']['top_bar']);
  }
}
