<?php

/**
 * @file
 * Template for YOURSITE theme.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements template_preprocess_html().
 */
function your_site_theme_preprocess_html(array &$variables): void {
  _your_site_theme_preprocess_navigation($variables);
}

/**
 * Preprocess administration navigation.
 */
function _your_site_theme_preprocess_navigation(array &$variables): void {
  // The 'hide_admin_navigation' setting removes the administration navigation
  // so pages can be themed while logged in as an administrator.
  if (Settings::get('hide_admin_navigation')) {
    unset($variables['page_top']['navigation']);
    unset($variables['page_top']['top_bar']);
  }
}
