<?php

/**
 * @file
 * Template for star wars theme.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements template_preprocess_html().
 */
function star_wars_preprocess_html(array &$variables): void {
  _star_wars_preprocess_admin_toolbar($variables);
}

/**
 * Preprocess admin toolbar.
 */
function _star_wars_preprocess_admin_toolbar(array &$variables): void {
  // Hide admin toolbar.
  if (Settings::get('hide_admin_toolbar') && !empty($variables['attributes']['class'])) {
    unset($variables['page_top']['toolbar']);
    $variables['attributes']['class'] = array_filter($variables['attributes']['class'], static fn($value): bool => !str_starts_with((string) $value, 'toolbar-'));
  }
}
