<?php

/**
 * @file
 * Core module for MYSITE.
 */

include_once 'mysite_core.constants.php';

/**
 * Include additional early bootstrap files.
 *
 * This allows to organise contrib module-related hook implementations into
 * standalone files.
 *
 * Note that most of the modules are not available at this stage and
 * another inclusion is required in hook_init() for performance reasons.
 */
$early_bootstrap_modules = module_list();
// Add more modules, inclusions for which are absolutely required at early
// stage.
$early_bootstrap_modules[] = 'system';
foreach ($early_bootstrap_modules as $module_name) {
  $module_include_file = dirname(__FILE__) . '/includes/' . $module_name . '.inc';
  if (file_exists($module_include_file)) {
    require_once $module_include_file;
  }
}
