<?php

/**
 * @file
 * Base module for YOURSITE.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements hook_theme().
 *
 * @phpstan-ignore-next-line
 */
function ys_base_theme(): array {
  return [
    'ys_base_counter_block' => [
      'variables' => [
        'counter_value' => 0,
      ],
      'template' => 'ys-base-counter-block',
    ],
  ];
}

/**
 * Implements hook_mail_alter().
 */
function ys_base_mail_alter(array &$message): void {
  // Allow to stop any mail send out through settings. Note if email
  // functionality needs to be tested, this code should be removed and
  // replaced with a dev mail system.
  if (Settings::get('suspend_mail_send')) {
    $message['send'] = FALSE;
  }
}
