#: Nginx container.
#:
#: All web requests are sent to this container.
ARG CLI_IMAGE
FROM ${CLI_IMAGE:-cli} as cli

# @see https://hub.docker.com/r/amazeeio/nginx-drupal/tags?page=1
# @see https://github.com/amazeeio/lagoon/tree/master/images/nginx-drupal
FROM amazeeio/nginx-drupal:v1.8.1

ENV WEBROOT=docroot

COPY --from=cli /app /app
