#: MariaDB container.
#:
# @see https://hub.docker.com/r/amazeeio/mariadb-drupal/tags?page=1
# @see https://github.com/amazeeio/lagoon/tree/master/images/mariadb-drupal
# @todo:d update docs
ARG IMAGE

FROM $IMAGE

USER root
COPY ./.docker/config/mariadb/my.cnf /etc/my.cnf.d/server.cnf
RUN fix-permissions /etc/my.cnf.d/

USER mysql
