ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM amazeeio/solr:6.6-drupal
# Uncomment below after installikng search_api_solr module.
# COPY --from=cli /app/docroot/sites/all/modules/contrib/search_api_solr/solr-conf/6.x/ /solr-conf/conf/
