<?php

/**
 * @file
 * Core module for YOURSITE.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_mail_alter().
 */
function your_site_core_mail_alter(&$message) {
  // Allow to stop any mail send out through settings. Note if email
  // functionality needs to be tested, this code should be removed and
  // replaced with a dev mail system.
  if (Settings::get('suspend_mail_send')) {
    $message['send'] = FALSE;
  }
}

/**
 * Implements hook_css_alter().
 */
function your_site_core_css_alter(&$css) {
  // Force disabling of CSS pre-processing if Livereload is enabled.
  if (Settings::get('livereload', FALSE)) {
    foreach ($css as $key => $value) {
      $css[$key]['preprocess'] = FALSE;
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function your_site_core_page_attachments_alter(array &$page) {
  // Attach Livereload if it is enabled in setting and the route is not admin
  // or the route is admin, but the current theme is admin as well.
  $route = \Drupal::routeMatch()->getRouteObject();
  $is_admin_route = \Drupal::service('router.admin_context')->isAdminRoute($route);
  $active_theme_is_admin = \Drupal::config('system.theme')->get('default') == \Drupal::config('system.theme')->get('admin');
  if (Settings::get('livereload', FALSE) && (!$is_admin_route || $active_theme_is_admin)) {
    _your_site_core_attach_livereload($page);
  }
}

/**
 * Helper to attach Livereload to the head of the page.
 */
function _your_site_core_attach_livereload(&$page) {
  $livereload_url = &drupal_static(__FUNCTION__);
  if (!$livereload_url) {
    $socket_file = \Drupal::service('file_system')->realpath('public://livereload.sock');
    if (file_exists($socket_file)) {
      $url = getenv('DREVOPS_LOCALDEV_URL');
      $port = trim(file_get_contents($socket_file));
      if (!empty($url) && is_numeric($port)) {
        $livereload_url = "$url:$port";
      }
    }
  }

  if ($livereload_url) {
    $page['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#attributes' => [
          'src' => "http://$livereload_url/livereload.js?snipver=1",
        ],
      ],
      'livereload',
    ];
  }
}
