#!/usr/bin/env bash
##
# Install the 'drevops/vortex-tooling' package into 'vendor/drevops/'.
#
# The 'drevops/vortex-tooling' package ships the Vortex shell scripts that
# host-side recipes (`ahoy download-db`, `ahoy deploy`, `ahoy doctor`,
# `ahoy update-vortex`, etc.) call before the project's full vendor/ tree
# has been built. This script installs only that single package so those
# recipes work on a fresh clone of a Vortex-based project.
#
# Behaviour:
#   * Idempotent: exits early if 'vendor/drevops/vortex-tooling/' already
#     exists.
#   * Resolves the version from 'composer.lock' (preferred, exact version)
#     and falls back to the constraint declared in 'composer.json'.
#   * Installs the package into a temporary working directory and moves it
#     into 'vendor/drevops/' so the project's main composer state is not
#     touched.
#   * Applies any patches declared for 'drevops/vortex-tooling' so user
#     customisations carry through. Patches are read from (in order):
#     - 'patches.lock.json' (generated by 'cweagans/composer-patches' v2)
#     - 'composer.json' under 'extra.patches.drevops/vortex-tooling'
#     - the file referenced by 'composer.json' under 'extra.patches-file'
#
# shellcheck disable=SC1090,SC1091

set -eu
[ "${VORTEX_DEBUG-}" = "1" ] && set -x

# ------------------------------------------------------------------------------
# Helpers.
# ------------------------------------------------------------------------------

info() { printf "[INFO] %s\n" "${1}"; }
task() { printf "  > %s\n" "${1}"; }
note() { printf "      %s\n" "${1}"; }
fail() { printf "[FAIL] %s\n" "${1}" >&2; }

# Read patches for the tooling package from a JSON file using a PHP one-liner.
#
# Supports two layouts:
#   1. 'extra.patches.{package}: {description: path, ...}' (composer-patches
#      input format, used in 'composer.json').
#   2. 'patches.{package}: [{url: path, ...}, ...]' (composer-patches v2 lock
#      file format, used in 'patches.lock.json').
#
# Prints one patch file path per line.
read_patches() {
  local json_file="${1}"
  local package="drevops/vortex-tooling"

  [ ! -f "${json_file}" ] && return 0

  php -r '
    $file = $argv[1];
    $package = $argv[2];
    $data = json_decode((string) file_get_contents($file), true);
    if (!is_array($data)) { exit; }

    // composer-patches v2 lock file format.
    if (isset($data["patches"][$package]) && is_array($data["patches"][$package])) {
      foreach ($data["patches"][$package] as $entry) {
        if (is_array($entry) && isset($entry["url"])) {
          echo $entry["url"], "\n";
        }
      }
      return;
    }

    // composer.json extra.patches format.
    if (isset($data["extra"]["patches"][$package]) && is_array($data["extra"]["patches"][$package])) {
      foreach ($data["extra"]["patches"][$package] as $value) {
        echo $value, "\n";
      }
    }
  ' -- "${json_file}" "${package}"
}

# Read the value of 'extra.patches-file' from composer.json, if defined.
read_patches_file_setting() {
  [ ! -f composer.json ] && return 0

  php -r '
    $data = json_decode((string) file_get_contents("composer.json"), true);
    if (is_array($data) && isset($data["extra"]["patches-file"])) {
      echo $data["extra"]["patches-file"];
    }
  '
}

# Apply a single patch file inside the installed tooling package directory.
apply_patch() {
  local patch_file="${1}"

  if [ ! -f "${patch_file}" ]; then
    fail "Patch file not found: ${patch_file}"
    exit 1
  fi

  task "Applying patch: ${patch_file}"
  patch --directory=vendor/drevops/vortex-tooling --strip=1 --input="${patch_file}"
}

# Apply all patches collected from the various supported sources.
apply_patches() {
  local patches
  patches=""

  # composer-patches v2 lockfile (most authoritative when present).
  if [ -f patches.lock.json ]; then
    patches="${patches}$(read_patches patches.lock.json)
"
  fi

  # Inline patches in composer.json.
  patches="${patches}$(read_patches composer.json)
"

  # External patches file referenced by composer.json.
  local patches_file
  patches_file="$(read_patches_file_setting)"
  if [ -n "${patches_file}" ]; then
    patches="${patches}$(read_patches "${patches_file}")
"
  fi

  # Deduplicate while preserving order, then apply.
  local seen=""
  local patch_file
  while IFS= read -r patch_file; do
    [ -z "${patch_file}" ] && continue
    case "${seen}" in
      *"|${patch_file}|"*) continue ;;
    esac
    seen="${seen}|${patch_file}|"
    apply_patch "${patch_file}"
  done <<EOF
${patches}
EOF
}

# ------------------------------------------------------------------------------
# Main.
# ------------------------------------------------------------------------------

# Nothing to do if the package is already installed.
if [ -d ./vendor/drevops/vortex-tooling ]; then
  exit 0
fi

info "Installing 'drevops/vortex-tooling' into 'vendor/drevops/'."

# ------------------------------------------------------------------------------
# Resolve the version constraint.
#
# Prefer the locked version from 'composer.lock' (an exact version) so we
# install the same version that 'composer install' would. Fall back to the
# constraint declared in 'composer.json' if the lock file is missing or does
# not contain the tooling package yet.
# ------------------------------------------------------------------------------

task "Resolving version constraint."

version=
if [ -f composer.lock ]; then
  version=$(composer show drevops/vortex-tooling --locked 2>/dev/null | awk '/^versions/{print $NF}') || true
fi

if [ -z "${version}" ]; then
  version=$(php -r 'echo json_decode(file_get_contents("composer.json"))->require->{"drevops/vortex-tooling"};')
fi

if [ -z "${version}" ]; then
  fail "Unable to resolve a version constraint for 'drevops/vortex-tooling'."
  note "Checked 'composer.lock' and 'composer.json'."
  exit 1
fi

note "Resolved version: ${version}"

# ------------------------------------------------------------------------------
# Install the package into a temporary working directory.
#
# Using a separate working dir means Composer only resolves the single
# tooling package and does not touch the project's main vendor/ directory or
# 'composer.lock'.
# ------------------------------------------------------------------------------

task "Preparing temporary install directory."

rm -rf vendor-temp
mkdir -p vendor-temp vendor/drevops

cat <<EOF >vendor-temp/composer.json
{
    "require": {
        "drevops/vortex-tooling": "${version}"
    }
}
EOF

#;< VORTEX_DEV
# In dev mode the package is not yet on Packagist, so add a path repository
# pointing at the in-tree copy. The installer strips this VORTEX_DEV-fenced
# block from consumer sites.
task "Adding in-tree path repository for development."
composer --working-dir=vendor-temp config repositories.vortex-tooling --json '{"type":"path","url":"../.vortex/tooling","options":{"symlink":false,"versions":{"drevops/vortex-tooling":"1.0.0"}}}'
#;> VORTEX_DEV

task "Running 'composer install' in temporary directory."
composer --working-dir=vendor-temp install --no-dev --no-scripts --no-plugins --no-interaction

task "Moving package into 'vendor/drevops/'."
mv vendor-temp/vendor/drevops/vortex-tooling vendor/drevops/
rm -rf vendor-temp

# ------------------------------------------------------------------------------
# Apply patches.
#
# 'cweagans/composer-patches' patches packages during 'composer install', but
# this script installs only the tooling package without plugins enabled.
# Replay the patch application manually so user customisations are honoured.
# ------------------------------------------------------------------------------

apply_patches

info "Done."
