#!/usr/bin/env php
<?php

/**
 * @file
 * Test fixture script for passing override operations.
 */

declare(strict_types=1);

namespace DrevOps\VortexTooling;

require_once __DIR__ . '/../../src/helpers.php';
execute_override(basename(__FILE__));

echo 'Original script should return code 0' . PHP_EOL;
