<?php

/**
 * @file
 * Base module for star wars.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements hook_mail_alter().
 */
function sw_base_mail_alter(array &$message): void {
  // The 'suspend_mail_send' setting stops all outgoing mail. Remove this and
  // use a development mail system when email sending needs to be tested.
  if (Settings::get('suspend_mail_send')) {
    $message['send'] = FALSE;
  }
}
