#!/usr/bin/env php
<?php

/**
 * @file
 * Vortex CLI entry point.
 */

declare(strict_types=1);

use DrevOps\VortexCli\Command\BuildCommand;
use DrevOps\VortexCli\Command\CheckRequirementsCommand;
use DrevOps\VortexCli\Command\InstallCommand;
use Symfony\Component\Console\Application;

require_once $GLOBALS['_composer_autoload_path'] ?? __DIR__ . '/vendor/autoload.php';

$application = new Application('Vortex Installer', getenv('VORTEX_INSTALLER_VERSION') ?: '@vortex-cli-version@');

$application->add(new InstallCommand());
$application->add(new CheckRequirementsCommand());
$application->add(new BuildCommand());

$application->setDefaultCommand('install');

$application->run();
