#!/usr/bin/env php
<?php

foreach ([$GLOBALS['_composer_autoload_path'] ?? NULL, __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
  if ($file && file_exists($file)) {
    require_once $file;
    unset($file);
    break;
  }
}

require __DIR__ . '/src/app.php';
