name: "Auto-label a PR with a conflict"

on:
  push:
  pull_request_target:
    types:
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: "CONFLICT"
          removeOnDirtyLabel: "Needs review"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
