# This action is used for Vortex maintenance. It will not be used in the scaffolded project.
name: Vortex - Test web-installer

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - 'feature/**'
      - 'bugfix/**'

jobs:
  vortex-test-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: npm ci
        working-directory: .vortex/webinstaller

      - name: Check coding standards
        run: npm run lint
        working-directory: .vortex/webinstaller

      - name: Run tests
        run: npm run test
        working-directory: .vortex/webinstaller

      - name: Upload logs as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.job}}-code-coverage-report
          path: .vortex/webinstaller/.logs
          include-hidden-files: true
